"""add event

Revision ID: 051130eff238
Revises: a8e22a16ef0a
Create Date: 2025-05-10 10:39:50.600226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text
# revision identifiers, used by Alembic.


revision: str = '051130eff238'
down_revision: Union[str, None] = 'a8e22a16ef0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('dorm_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dorm_id'], ['dorms.id'], onupdate='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('room', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('data', postgresql.JSONB(astext_type=Text()), nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'dorms', ['dorm_id'], ['id'], onupdate='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'dorms', ['dorm_id'], ['id'])
    op.drop_column('users', 'data')
    op.drop_column('users', 'room')
    op.drop_table('events')
    # ### end Alembic commands ###
