"""update dorms

Revision ID: 74e0c566e0f5
Revises: 70c9f8939c49
Create Date: 2025-05-10 15:18:40.613745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e0c566e0f5'
down_revision: Union[str, None] = '70c9f8939c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dorms', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dorms', type_='unique')
    # ### end Alembic commands ###
